# Generated by Django 4.1.1 on 2022-09-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=100)),
                ('text_color', models.CharField(max_length=100)),
                ('link_color', models.CharField(max_length=100)),
                ('button_color', models.CharField(max_length=100)),
                ('button_text_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('mission', models.TextField()),
                ('logo', models.ImageField(upload_to='brand/logo')),
                ('font', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='brand.colorpalette')),
            ],
        ),
    ]
