# Generated by Django 4.1.1 on 2022-09-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='username',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
    ]
