# Generated by Django 4.1.1 on 2022-09-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=100),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='button_color',
            field=models.CharField(default='#000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=100),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='link_color',
            field=models.CharField(default='#0077ff', max_length=100),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='text_color',
            field=models.CharField(default='#000000', max_length=100),
        ),
    ]
