# Generated by Django 4.1.1 on 2022-09-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_font_alter_colorpalette_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='color_palette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='brand.colorpalette'),
        ),
    ]
