# Generated by Django 4.1.1 on 2022-09-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_brand_facebook_url_brand_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='mission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='button_color',
            field=models.CharField(default='#1A202C', max_length=100),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='link_color',
            field=models.CharField(default='#3182ce', max_length=100),
        ),
    ]
